---
dependencies:
  flutter:
    sdk: flutter
description: A Flutter package for adaptive navigation.
dev_dependencies:
  auto_exporter: ^4.0.0
  build_runner: ^2.0.0
  flutter_lints: any
  flutter_test:
    sdk: flutter
  very_good_analysis: any
environment:
  flutter: ">=1.17.0"
  sdk: ^3.8.0
homepage: https://github.com/normidar/colaxy_adaptive_scaffold
name: colaxy_adaptive_scaffold
topics:
  - adaptive
  - scaffold
  - navigation
  - material
  - flutter
version: 0.0.1
